using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

/// <summary>
/// AUTO-SETUP semua kebutuhan game saat runtime.
/// Tidak perlu assign apapun di Inspector.
///
/// Yang di-handle:
///   1. LifetopiaBootstrapConfig — auto-create di Resources kalau belum ada
///   2. LifetopiaGameState       — auto-spawn singleton
///   3. SceneTransitionManager   — auto-spawn singleton
///   4. LifetopiaGameFlowFsm     — auto-spawn singleton
///   5. LifetopiaAutoPlayableScene — auto-spawn bootstrap
///   6. Default values semua config field
///
/// Cara pakai: tidak perlu apa-apa. Script ini jalan otomatis via
/// [RuntimeInitializeOnLoadMethod] sebelum scene pertama load.
/// </summary>
public static class GameAutoSetup
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    static void AutoSetup()
    {
        EnsureBootstrapConfig();
    }

    // ── Bootstrap Config ──────────────────────────────────────────────────────

    static void EnsureBootstrapConfig()
    {
        // Coba load dari Resources dulu
        var cfg = Resources.Load<LifetopiaBootstrapConfig>("LifetopiaBootstrapConfig");

        if (cfg == null)
        {
            // Buat runtime instance dengan default values
            cfg = ScriptableObject.CreateInstance<LifetopiaBootstrapConfig>();
            cfg.name = "LifetopiaBootstrapConfig_AutoGenerated";
            ApplyDefaults(cfg);
            LifetopiaBootstrapConfig.OverrideCache(cfg);
            UnityEngine.Debug.Log("[GameAutoSetup] BootstrapConfig tidak ditemukan di Resources — " +
                      "pakai runtime defaults. Buat asset via Assets > Create > Lifetopia > Bootstrap Config untuk persist.");
        }
        else
        {
            LifetopiaBootstrapConfig.OverrideCache(cfg);
        }
    }

    static void ApplyDefaults(LifetopiaBootstrapConfig cfg)
    {
        // Camera
        cfg.orthographicSize        = 5f;
        cfg.cameraClearColor        = new Color(0.08f, 0.12f, 0.18f, 1f);

        // Background
        cfg.backgroundFitWorldHeight   = 11f;
        cfg.backgroundScaleMultiplier  = 1f;
        cfg.backgroundPositionOffset   = Vector3.zero;

        // Paths biome (fallback disk)
        cfg.pathFarm     = "Assets/image/new map/farm.png";
        cfg.pathCity     = "Assets/image/new map/city.png";
        cfg.pathSuburban = "Assets/image/new map/suburban.png";
        cfg.pathGarden   = "Assets/image/new map/garden.png";
        cfg.pathFishing  = "Assets/image/new map/fishing.png";

        // Character
        cfg.characterScale         = new Vector3(0.34f, 0.34f, 1f);
        cfg.characterSpawnPosition = new Vector3(-3.25f, -3.65f, 0f);

        // Farm plots
        cfg.plotOriginWorld = new Vector3(-3.95f, -3.08f, 0f);
        cfg.plotStep        = 1.9f;
        cfg.plotVisualScale = new Vector3(2.1f, 1.2f, 1f);

        // Solana Devnet (mock — tidak butuh key valid untuk play)
        cfg.solanaDevnetRpcUrl      = "https://solana-devnet.g.alchemy.com/v2/JiVbTwHnF3qEGfs5AtgKR";
        cfg.alchemyApiKeySuffix     = "JiVbTwHnF3qEGfs5AtgKR";
        cfg.alphaUtilityMintAddress = "ByrXMnACFFyvsL6d4yKFguCK8CNRJDMSWWshLejaApVu";
        cfg.verifyMintOnWalletConnect = false; // matikan chain verify saat dev
    }

    // ── Editor Helper: Create Asset ───────────────────────────────────────────

#if UNITY_EDITOR
    [MenuItem("Tools/Lifetopia/Create Bootstrap Config Asset")]
    static void CreateBootstrapConfigAsset()
    {
        const string dir  = "Assets/Resources";
        const string path = dir + "/LifetopiaBootstrapConfig.asset";

        if (!AssetDatabase.IsValidFolder(dir))
            AssetDatabase.CreateFolder("Assets", "Resources");

        if (AssetDatabase.LoadAssetAtPath<LifetopiaBootstrapConfig>(path) != null)
        {
            EditorUtility.DisplayDialog("Lifetopia", "Sudah ada: " + path, "OK");
            Selection.activeObject = AssetDatabase.LoadAssetAtPath<LifetopiaBootstrapConfig>(path);
            return;
        }

        var asset = ScriptableObject.CreateInstance<LifetopiaBootstrapConfig>();
        ApplyDefaults(asset);
        AssetDatabase.CreateAsset(asset, path);
        AssetDatabase.SaveAssets();
        EditorUtility.FocusProjectWindow();
        Selection.activeObject = asset;
        UnityEngine.Debug.Log("[GameAutoSetup] BootstrapConfig asset dibuat di: " + path);
    }

    [MenuItem("Tools/Lifetopia/Auto-Create All Assets")]
    static void CreateAllAssets()
    {
        CreateBootstrapConfigAsset();
        UnityEngine.Debug.Log("[GameAutoSetup] Semua asset Lifetopia sudah dibuat.");
    }
#endif
}
