begin;

create table public.community_announcements(id uuid primary key default gen_random_uuid(),title text not null check(length(trim(title)) between 4 and 120),body text not null check(length(trim(body)) between 10 and 2000),published_by uuid not null references public.profiles(id),published_at timestamptz not null default now(),is_active boolean not null default true);
create table public.community_notifications(id uuid primary key default gen_random_uuid(),recipient_id uuid not null references public.profiles(id) on delete cascade,type text not null check(type in('official_announcement','comment_reply')),actor_id uuid references public.profiles(id) on delete set null,announcement_id uuid references public.community_announcements(id) on delete cascade,post_id uuid references public.community_posts(id) on delete cascade,comment_id uuid references public.community_comments(id) on delete cascade,title text not null,body text not null,dedupe_key text not null,read_at timestamptz,created_at timestamptz not null default now(),unique(recipient_id,dedupe_key));
create index community_notifications_recipient_idx on public.community_notifications(recipient_id,read_at,created_at desc);

create table public.community_guilds(id uuid primary key default gen_random_uuid(),slug text not null unique check(slug~'^[a-z0-9][a-z0-9-]{2,31}$'),name text not null check(length(trim(name)) between 3 and 40),description text not null check(length(trim(description)) between 10 and 500),owner_id uuid not null references public.profiles(id),join_policy text not null default'open' check(join_policy in('open','approval')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(owner_id));
create table public.community_guild_members(guild_id uuid not null references public.community_guilds(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,role text not null default'member' check(role in('owner','member')),status text not null default'active' check(status in('pending','active')),joined_at timestamptz not null default now(),primary key(guild_id,user_id));
create index community_guild_members_user_idx on public.community_guild_members(user_id,status);

alter table public.community_announcements enable row level security;alter table public.community_notifications enable row level security;alter table public.community_guilds enable row level security;alter table public.community_guild_members enable row level security;
revoke all on public.community_announcements,public.community_notifications,public.community_guilds,public.community_guild_members from public,anon,authenticated;
grant select on public.community_announcements,public.community_guilds,public.community_guild_members to anon,authenticated;grant select on public.community_notifications to authenticated;
create policy announcements_public_read on public.community_announcements for select to anon,authenticated using(is_active);
create policy notifications_read_own on public.community_notifications for select to authenticated using(recipient_id=auth.uid());
create policy guilds_public_read on public.community_guilds for select to anon,authenticated using(true);
create policy guild_members_public_active_or_related on public.community_guild_members for select to anon,authenticated using(status='active' or user_id=auth.uid() or exists(select 1 from public.community_guilds g where g.id=guild_id and g.owner_id=auth.uid()));

create or replace function public.notify_comment_reply()returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare v_recipient uuid;v_post uuid;begin if new.parent_comment_id is null then return new;end if;select author_id,post_id into v_recipient,v_post from public.community_comments where id=new.parent_comment_id;if v_recipient is null or v_recipient=new.author_id then return new;end if;insert into public.community_notifications(recipient_id,type,actor_id,post_id,comment_id,title,body,dedupe_key)values(v_recipient,'comment_reply',new.author_id,v_post,new.id,'New reply to your comment',left(new.content,180),'reply:'||new.id::text)on conflict do nothing;return new;end;$$;
create trigger notify_comment_reply_after_insert after insert on public.community_comments for each row execute function public.notify_comment_reply();

create or replace function public.publish_community_announcement(p_title text,p_body text)returns uuid language plpgsql security definer set search_path=pg_catalog,public as $$declare v_actor uuid:=auth.uid();v_role text;v_id uuid;begin select role into v_role from public.profiles where id=v_actor;if v_role not in('founder','admin','moderator')then raise exception'announcement_staff_required'using errcode='42501';end if;insert into public.community_announcements(title,body,published_by)values(trim(p_title),trim(p_body),v_actor)returning id into v_id;insert into public.community_notifications(recipient_id,type,actor_id,announcement_id,title,body,dedupe_key)select p.id,'official_announcement',v_actor,v_id,trim(p_title),left(trim(p_body),300),'announcement:'||v_id::text from public.profiles p;return v_id;end;$$;
create or replace function public.mark_community_notification_read(p_notification_id uuid default null)returns integer language plpgsql security definer set search_path=pg_catalog,public as $$declare v_count integer;begin update public.community_notifications set read_at=coalesce(read_at,now())where recipient_id=auth.uid()and(p_notification_id is null or id=p_notification_id);get diagnostics v_count=row_count;return v_count;end;$$;

create or replace function public.create_community_guild(p_name text,p_slug text,p_description text,p_join_policy text)returns uuid language plpgsql security definer set search_path=pg_catalog,public as $$declare v_user uuid:=auth.uid();v_id uuid;begin if v_user is null then raise exception'authentication_required'using errcode='42501';end if;if p_join_policy not in('open','approval')then raise exception'invalid_join_policy'using errcode='22023';end if;insert into public.community_guilds(name,slug,description,owner_id,join_policy)values(trim(p_name),lower(trim(p_slug)),trim(p_description),v_user,p_join_policy)returning id into v_id;insert into public.community_guild_members(guild_id,user_id,role,status)values(v_id,v_user,'owner','active');return v_id;end;$$;
create or replace function public.join_community_guild(p_guild_id uuid)returns text language plpgsql security definer set search_path=pg_catalog,public as $$declare v_user uuid:=auth.uid();v_policy text;v_status text;begin if v_user is null then raise exception'authentication_required'using errcode='42501';end if;select join_policy into v_policy from public.community_guilds where id=p_guild_id;if not found then raise exception'guild_not_found'using errcode='P0002';end if;v_status:=case when v_policy='open'then'active'else'pending'end;insert into public.community_guild_members(guild_id,user_id,role,status)values(p_guild_id,v_user,'member',v_status)on conflict(guild_id,user_id)do update set status=excluded.status where public.community_guild_members.status='pending';return v_status;end;$$;
create or replace function public.leave_community_guild(p_guild_id uuid)returns boolean language plpgsql security definer set search_path=pg_catalog,public as $$declare v_user uuid:=auth.uid();begin if exists(select 1 from public.community_guilds where id=p_guild_id and owner_id=v_user)then raise exception'owner_cannot_leave'using errcode='22023';end if;delete from public.community_guild_members where guild_id=p_guild_id and user_id=v_user;return found;end;$$;
create or replace function public.review_guild_join_request(p_guild_id uuid,p_user_id uuid,p_approve boolean)returns boolean language plpgsql security definer set search_path=pg_catalog,public as $$begin if not exists(select 1 from public.community_guilds where id=p_guild_id and owner_id=auth.uid())then raise exception'guild_owner_required'using errcode='42501';end if;if p_approve then update public.community_guild_members set status='active',joined_at=now()where guild_id=p_guild_id and user_id=p_user_id and status='pending';else delete from public.community_guild_members where guild_id=p_guild_id and user_id=p_user_id and status='pending';end if;return found;end;$$;

revoke all on function public.notify_comment_reply(),public.publish_community_announcement(text,text),public.mark_community_notification_read(uuid),public.create_community_guild(text,text,text,text),public.join_community_guild(uuid),public.leave_community_guild(uuid),public.review_guild_join_request(uuid,uuid,boolean)from public,anon;
grant execute on function public.publish_community_announcement(text,text),public.mark_community_notification_read(uuid),public.create_community_guild(text,text,text,text),public.join_community_guild(uuid),public.leave_community_guild(uuid),public.review_guild_join_request(uuid,uuid,boolean)to authenticated;
commit;
